### ISSUE TITLE
Localization - Norwegian (Norsk) <no-no.cfg>   

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Biomatic#23]
From Localization created by [zer0Kerbal](https://github.com/zer0Kerbal): zer0Kerbal/Localization#12  

Localization - [Norwegian (Norsk)][NO] <no-no.cfg>  

### GameData

- [ ] add en-us.cfg  

### Translation

- [ ] [![Norsk][NO]][NO] [Norwegian (Norsk)][NO] <no-no.cfg>  

[NO]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Norwegian-flag-sm.png "Norsk"

### Update Documentation

- [ ]  mod Readme 🔢 
- [ ]  releaseNotes.md 🧾 

### GitHub Issues

- [ ] assign to zer0Kerbal
- [ ] assign projects (user and repo)
- [ ] assign label: Localization
- [ ] assign label: help-wanted
- [ ] assign milestone: Localization - [Norwegian (Norsk)][NO] <no-no.cfg>

### Update Social Media

- [ ] CurseForge
- [ ] CKAN
- [ ] Forum
- [ ] GitHub
- [ ] Patreon
- [ ] Reddit
- [ ] SpaceDock

### Wiki

- [ ] update localization list 
  

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization" 
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

**Comment by dotkim** [comment]
Hey, came in from issuehub and can do my best to translate the .cfg file if you want.
Do you just want a copy of en-us.cfg named no-no.cfg and translated?

**Comment by zer0Kerbal** [comment]
> Hey, came in from issuehub and can do my best to translate the .cfg file if you want. Do you just want a copy of en-us.cfg named no-no.cfg and translated?

Ja, det hadde vært flott! ( yes please! 😄 )

**Comment by dotkim** [comment]
@zer0Kerbal Could you provide some context for these values? I'm not really sure what they would mean:
#Biomatic_Situation_SrfSplashed = Splashed (Not sure what this would indicate?)
#Biomatic_Label_Warp = De-warp (I cant find a translation for warping if it is about speed)

**Comment by zer0Kerbal** [comment]
Yes 
- `Splashed` - as in the space capsule has landed in the water - `Splashed` down
- `Warp`/`De-Warp` - like Star Trek - `to go very fast` - `to stop going very fast but not stop` (turn off the turbo button so to speak)

hope this helps
